server:
  name: ggb_server
  port: 8080
  mode: "prod"  #test、prod、dev

db:
  host: "localhost"
  port: 3306
  user: "root"
  password: "Ai_edu2025"
  name: "ggb_gen"
  max_idle_conns: 10
  max_open_conns: 100

jwt:
  secret: "secret"
  expire: 30 #min

static:
  path: "static/upload"

log:
  level: "info" # debug, info, warn, error, fatal
  file_path: "/var/glog/my_app/app.glog"
  enable_console_output: true

ai_model:
  deepseek:
    apiKey: "sk-9320e048d0d04f37a99eaa4d984bbe86"  # sk-qKo22ROUL4WXXh1UzY7fPtGjUWBcluE1nxvRiJUNC9UfoBD3
  stepfun:
    apiKey: "4qNfUujEuOkN0WWP9TNHRDfedWM6KWVE8KnErfKRicGBfj9JWkKA4QYktcqLPr4Ch"
  doubao:
    apiKey: "c618f374-1078-46c7-ba51-a4a7fcd8294e"

